# -*- coding: utf-8 -*-
"""cifar10EDA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s-9ycfrCvoJn5tEcUox2zzynwwtkqBaX
"""

# ============================================================
# Exploratory Data Analysis (EDA) for CIFAR-10 Dataset
# ============================================================

import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras import datasets

# ---------------------- Load Dataset ------------------------
(X_train, y_train), (X_test, y_test) = datasets.cifar10.load_data()

class_names = ['Airplane', 'Automobile', 'Bird', 'Cat', 'Deer',
               'Dog', 'Frog', 'Horse', 'Ship', 'Truck']

# ---------------------- Dataset Overview --------------------
print("Training data shape :", X_train.shape)
print("Training labels shape:", y_train.shape)
print("Testing data shape  :", X_test.shape)
print("Testing labels shape:", y_test.shape)

# ---------------------- Pixel Statistics --------------------
print("Pixel value range:", X_train.min(), "to", X_train.max())

# ---------------------- Class Distribution ------------------
unique, counts = np.unique(y_train, return_counts=True)

plt.figure(figsize=(8,4))
plt.bar([class_names[i] for i in unique], counts)
plt.title("Class Distribution in CIFAR-10 Training Set")
plt.xlabel("Class")
plt.ylabel("Number of Images")
plt.xticks(rotation=45)
plt.show()

# ---------------------- Sample Images -----------------------
plt.figure(figsize=(10,10))
for i in range(16):
    plt.subplot(4,4,i+1)
    plt.imshow(X_train[i])
    plt.title(class_names[y_train[i][0]])
    plt.axis("off")
plt.suptitle("Sample Images from CIFAR-10 Dataset")
plt.show()

# ---------------------- Mean Image --------------------------
mean_image = np.mean(X_train, axis=0)

plt.figure(figsize=(4,4))
plt.imshow(mean_image.astype("uint8"))
plt.title("Mean Image of CIFAR-10 Dataset")
plt.axis("off")
plt.show()

# ---------------------- Channel-wise Statistics -------------
mean_r, mean_g, mean_b = np.mean(X_train[:,:,:,0]), np.mean(X_train[:,:,:,1]), np.mean(X_train[:,:,:,2])
std_r, std_g, std_b   = np.std(X_train[:,:,:,0]),  np.std(X_train[:,:,:,1]),  np.std(X_train[:,:,:,2])

print("Channel-wise Mean (R, G, B):", mean_r, mean_g, mean_b)
print("Channel-wise Std  (R, G, B):", std_r, std_g, std_b)